export const THEMES = {
  light: {
    name: "Light",
    "--color-background-primary": "#ffffff",
    "--color-background-secondary": "#f5f5f5",
    "--color-border-secondary": "#d1d1d1",
    "--color-border-tertiary": "#e5e5e5",
    "--color-text-primary": "#111111",
    "--color-text-secondary": "#555555",
    "--color-text-tertiary": "#888888",
    "--font-sans": "system-ui, -apple-system, sans-serif",
  },
  dark: {
    name: "Dark",
    "--color-background-primary": "#1a1a1a",
    "--color-background-secondary": "#252525",
    "--color-border-secondary": "#404040",
    "--color-border-tertiary": "#303030",
    "--color-text-primary": "#f0f0f0",
    "--color-text-secondary": "#a0a0a0",
    "--color-text-tertiary": "#666666",
    "--font-sans": "system-ui, -apple-system, sans-serif",
  },
  ocean: {
    name: "Ocean",
    "--color-background-primary": "#0d1b2a",
    "--color-background-secondary": "#1b2e42",
    "--color-border-secondary": "#2a4560",
    "--color-border-tertiary": "#1e3550",
    "--color-text-primary": "#e0f0ff",
    "--color-text-secondary": "#7aafcc",
    "--color-text-tertiary": "#4a7a99",
    "--font-sans": "system-ui, -apple-system, sans-serif",
  },
  dusk: {
    name: "Dusk",
    "--color-background-primary": "#1c1420",
    "--color-background-secondary": "#271b2e",
    "--color-border-secondary": "#3d2a4a",
    "--color-border-tertiary": "#302038",
    "--color-text-primary": "#f0e8ff",
    "--color-text-secondary": "#a888cc",
    "--color-text-tertiary": "#6a4888",
    "--font-sans": "system-ui, -apple-system, sans-serif",
  },
  sand: {
    name: "Sand",
    "--color-background-primary": "#faf7f2",
    "--color-background-secondary": "#f0ebe0",
    "--color-border-secondary": "#d4c9b0",
    "--color-border-tertiary": "#e5dece",
    "--color-text-primary": "#2c2418",
    "--color-text-secondary": "#6b5c40",
    "--color-text-tertiary": "#9c8860",
    "--font-sans": "system-ui, -apple-system, sans-serif",
  },
};

export const THEME_IDS = Object.keys(THEMES);
